### ISSUE TITLE
Error when use robotlegsJS-Pixi with reflect-metadata@0.1.9

### ISSUE THREAD

**Issue by quyetvivn** [GoodgameStudios/RobotlegsJS-Pixi#25]
Cannot assign to read only property 'mediatorMap' of object '#<Config>'
Reflect-metadata changelog: https://github.com/rbuckton/reflect-metadata/releases/tag/v0.1.9

**Comment by tiagoschenkel** [comment]
Hi @quyetvivn!

Finally I figured out the reason for this problem. The **typedoc** dev dependency is not used anymore, but it's causing conflicts related to the **typescript** version. They are adding the typescript in the ** dependencies** section, not in the **devDependencies**. This forces the **NPM** or **Yarn** to get their used version of typescripq, and since we are using another version, our build was breaking and was pretty difficult to understand why.

I'm planning to solve this problem soon, will keep this issue updated.
